# Generated by Django 2.1.5 on 2019-01-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sungjuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이 름')),
                ('kor', models.IntegerField(default=0, verbose_name='국 어')),
                ('mat', models.IntegerField(default=0, verbose_name='수 학')),
                ('eng', models.IntegerField(default=0, verbose_name='영 어')),
            ],
            options={
                'verbose_name': '성적',
                'verbose_name_plural': '성적셋',
                'ordering': ['name'],
            },
        ),
    ]
